<?xml version="1.0" encoding="UTF-8"?>
<module external.linked.project.id=":Topics-Array_exceptions-A_line_that_throws_an_exception:main" external.linked.project.path="$MODULE_DIR$/../../../../../Topics/Array exceptions/A line that throws an exception" external.root.project.path="$MODULE_DIR$/../../../../.." external.system.id="GRADLE" external.system.module.group="Battleship" external.system.module.type="sourceSet" external.system.module.version="unspecified" type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager" LANGUAGE_LEVEL="JDK_11">
    <output url="file://$MODULE_DIR$/../../../../../Topics/Array exceptions/A line that throws an exception/out/production/classes" />
    <exclude-output />
    <content url="file://$MODULE_DIR$/../../../../../Topics/Array exceptions/A line that throws an exception/src">
      <sourceFolder url="file://$MODULE_DIR$/../../../../../Topics/Array exceptions/A line that throws an exception/src" isTestSource="false" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
  </component>
</module>